### ISSUE TITLE
Document tracking specifications

### ISSUE THREAD

**Issue by livlab** [thecarebot/carebot#73]
"Do we have a page with specs for the time bucket metrics and the others we’re considering? eg (Time buckets: “Element is entirely visible” or “Any part of the element is visible” … “buckets: 10s up to…”)"

**Comment by livlab** [comment]
- [ ] 'Linger Rate' indicator
- [ ] 'graphic on view' metric
- [ ] 'Story Completion Rate' indicator
- [ ] 'scroll depth up to comments' metric

**Comment by livlab** [comment]
This is going to become a task for the code convening.

**Comment by livlab** [comment]
https://thecarebot.github.io/metrics
